package app_simpeg;
import javax.swing.JFrame;
public class Menu extends javax.swing.JFrame {
    public Menu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        btnToolbarPegawai = new javax.swing.JButton();
        btnToolbarCari = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnToolbarLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuPegawai = new javax.swing.JMenuItem();
        menuGolongan = new javax.swing.JMenuItem();
        menuCari = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setRollover(true);

        btnToolbarPegawai.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnToolbarPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-user.png"))); // NOI18N
        btnToolbarPegawai.setText("Data Pegawai");
        btnToolbarPegawai.setFocusable(false);
        btnToolbarPegawai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToolbarPegawai.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btnToolbarPegawai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnToolbarPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolbarPegawaiActionPerformed(evt);
            }
        });
        jToolBar1.add(btnToolbarPegawai);

        btnToolbarCari.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnToolbarCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnToolbarCari.setText("Cari Pegawai");
        btnToolbarCari.setFocusable(false);
        btnToolbarCari.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToolbarCari.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btnToolbarCari.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnToolbarCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolbarCariActionPerformed(evt);
            }
        });
        jToolBar1.add(btnToolbarCari);
        jToolBar1.add(jSeparator3);

        btnToolbarLogout.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnToolbarLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sign-out.png"))); // NOI18N
        btnToolbarLogout.setText("Log Out");
        btnToolbarLogout.setFocusable(false);
        btnToolbarLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToolbarLogout.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btnToolbarLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnToolbarLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolbarLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnToolbarLogout);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu2.setText("Master Data");

        menuPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-user.png"))); // NOI18N
        menuPegawai.setText("Pegawai");
        menuPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPegawaiActionPerformed(evt);
            }
        });
        jMenu2.add(menuPegawai);

        menuGolongan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/connect-people.png"))); // NOI18N
        menuGolongan.setText("Golongan");
        menuGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGolonganActionPerformed(evt);
            }
        });
        jMenu2.add(menuGolongan);

        menuCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        menuCari.setText("Cari Pegawai");
        menuCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCariActionPerformed(evt);
            }
        });
        jMenu2.add(menuCari);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Utility");

        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sign-out.png"))); // NOI18N
        menuLogout.setText("Log Out");
        jMenu3.add(menuLogout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToolbarPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolbarPegawaiActionPerformed
        new FormPegawai().setVisible(true);
    }//GEN-LAST:event_btnToolbarPegawaiActionPerformed

    private void btnToolbarCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolbarCariActionPerformed
        new FormPencarian().setVisible(true);
    }//GEN-LAST:event_btnToolbarCariActionPerformed

    private void btnToolbarLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolbarLogoutActionPerformed
        new Menu().setVisible(false);
    }//GEN-LAST:event_btnToolbarLogoutActionPerformed

    private void menuCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCariActionPerformed
        new FormPencarian().setVisible(true);
    }//GEN-LAST:event_menuCariActionPerformed

    private void menuPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPegawaiActionPerformed
        new FormPegawai().setVisible(true);
    }//GEN-LAST:event_menuPegawaiActionPerformed

    private void menuGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGolonganActionPerformed
        new FormGolongan().setVisible(true);
    }//GEN-LAST:event_menuGolonganActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu frame = new Menu(); 
                frame.setVisible(true);
                // new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnToolbarCari;
    private javax.swing.JButton btnToolbarLogout;
    private javax.swing.JButton btnToolbarPegawai;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuCari;
    private javax.swing.JMenuItem menuGolongan;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuPegawai;
    // End of variables declaration//GEN-END:variables
}
